export const variantStyles = {
  primary: [
    "bg-indigo-700",
    "border-none",
    "disabled:bg-neutral-100",
    "focus:border-neutral-200",
    "hover:bg-indigo-800",
    "focus:ring",
    "focus:ring-indigo-100",
  ],
  secondary: [
    "bg-white",
    "shadow-md",
    "border-[0.5px]",
    "border-solid",
    "border-neutral-200",
    "disabled:bg-neutral-100",
    "hover:bg-neutral-50",
    "focus:ring",
    "focus:ring-indigo-100",
  ],
  tertiary: [
    "bg-none",
    "border-none",
    "hover:bg-neutral-50",
    "focus:ring",
    "focus:ring-indigo-100",
  ],
  link_color: [
    "bg-none",
    "border-none",
    "focus:ring",
    "focus:ring-indigo-100",
    "p-0",
  ],
  link_grey: [
    "border-none",
    "bg-none",
    "focus:ring",
    "focus:ring-indigo-100",
    "p-0",
  ],
  destructive: [
    "bg-red-600",
    "border-none",
    "hover:bg-red-700",
    "disabled:bg-transparent",
    "focus:ring",
    "focus:ring-red-100",
  ],
}
