/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NavbarImport } from './routes/navbar'
import { Route as ButtonsImport } from './routes/buttons'
import { Route as BadgesImport } from './routes/badges'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const NavbarRoute = NavbarImport.update({
  id: '/navbar',
  path: '/navbar',
  getParentRoute: () => rootRoute,
} as any)

const ButtonsRoute = ButtonsImport.update({
  id: '/buttons',
  path: '/buttons',
  getParentRoute: () => rootRoute,
} as any)

const BadgesRoute = BadgesImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesImport
      parentRoute: typeof rootRoute
    }
    '/buttons': {
      id: '/buttons'
      path: '/buttons'
      fullPath: '/buttons'
      preLoaderRoute: typeof ButtonsImport
      parentRoute: typeof rootRoute
    }
    '/navbar': {
      id: '/navbar'
      path: '/navbar'
      fullPath: '/navbar'
      preLoaderRoute: typeof NavbarImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/badges': typeof BadgesRoute
  '/buttons': typeof ButtonsRoute
  '/navbar': typeof NavbarRoute
  '/about': typeof AboutLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/badges': typeof BadgesRoute
  '/buttons': typeof ButtonsRoute
  '/navbar': typeof NavbarRoute
  '/about': typeof AboutLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/badges': typeof BadgesRoute
  '/buttons': typeof ButtonsRoute
  '/navbar': typeof NavbarRoute
  '/about': typeof AboutLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/badges' | '/buttons' | '/navbar' | '/about'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/badges' | '/buttons' | '/navbar' | '/about'
  id: '__root__' | '/' | '/badges' | '/buttons' | '/navbar' | '/about'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  BadgesRoute: typeof BadgesRoute
  ButtonsRoute: typeof ButtonsRoute
  NavbarRoute: typeof NavbarRoute
  AboutLazyRoute: typeof AboutLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  BadgesRoute: BadgesRoute,
  ButtonsRoute: ButtonsRoute,
  NavbarRoute: NavbarRoute,
  AboutLazyRoute: AboutLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/badges",
        "/buttons",
        "/navbar",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/badges": {
      "filePath": "badges.tsx"
    },
    "/buttons": {
      "filePath": "buttons.tsx"
    },
    "/navbar": {
      "filePath": "navbar.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
